name: Continuous integration

on:
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install SonarCloud dependencies
      run: sudo apt-get update && sudo apt-get install default-jre-headless -y
    - name: Install SonarCloud dotnet
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Start SonarCloud analysis
      run: dotnet sonarscanner begin -k:Sirups.Essentials.Mvc -d:sonar.host.url="https://sonarcloud.io" -o:sirups -d:sonar.login=${{secrets.SONAR_KEY}} -d:sonar.branch.name=${GITHUB_REF##*/}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: End SonarCloud analysis
      run: dotnet sonarscanner end -d:sonar.login=${{secrets.SONAR_KEY}}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
