name: Release

on:
  push:
    branches: 
      - release
env:
  version: 0.0.$GITHUB_RUN_NUMBER
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore "/p:Version=${version}"
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --include-symbols --include-source
    - name: Push
      run: dotnet nuget push ./src/Sirups.Essentials.Mvc/bin/Release/Sirups.Essentials.Mvc*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_APIKEY}}
    - name: Create a Release
      uses: actions/create-release@v1
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: ${version}
        # The name of the release. For example, `Release v1.0.1`
        release_name: Release v${version} 
        # Text describing the contents of the tag.
        #body:  # optional
        # Path to file with information about the tag.
        #body_path: # optional
        # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
        draft: true # optional
        # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
        #prerelease: # optional
        # Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit
        #commitish: # optional
